Update aios

diff --git a/aios b/aios
--- a/aios
+++ b/aios
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-SCRIPT_VERSION="2025.03.07-02-04"
+SCRIPT_VERSION="2025.03.07-02-05"
 echo -e "\033[7;40mUpdated to version $SCRIPT_VERSION aios \033[0m"
 
 # =========================================================
@@ -628,7 +628,13 @@ download() {
         debug_log "DEBUG" "Local version is $local_version"
         debug_log "DEBUG" "Remote version is $remote_version"
 
-        if ! $WIGET "$install_path" "$remote_url"; then
+        if ! $BASE_WGET "$install_path" "$remote_url"; then
+            debug_log "ERROR" "Download failed: $file_name is empty"
+            echo "Error: Download failed: $file_name is empty." >&2
+            return 1
+        fi
+
+        if [ ! -s "$install_path" ]; then
             debug_log "ERROR" "Download failed: $file_name is empty"
             echo "Error: Download failed: $file_name is empty." >&2
             return 1
@@ -663,7 +669,7 @@ download() {
         debug_log "DEBUG" "Bin path: $BIN_PATH"
         debug_log "DEBUG" "Bin dir: $BIN_DIR"
         debug_log "DEBUG" "Bin file: $BIN_FILE"
-        mv "$BASE_DIR/$file_name" "$BIN_PATH"
+        mv "$install_path" "$BIN_PATH"
         if [ ! -f "$aios_update" ]; then
             read_message="read "
             touch "$aios_update"
