Update aios

diff --git a/aios b/aios
--- a/aios
+++ b/aios
@@ -598,6 +598,16 @@ download() {
         fi
         return 0
     fi
+
+    # スクリプトの読み込み
+    if [ "$read_mode" = "true" ] || echo "$file_name" | grep -q '^common-.*\.sh$'; then
+        if [ -f "$install_path" ]; then
+            . "$install_path"
+            debug_log "INFO" "Sourced: $install_path"
+        else
+            debug_log "ERROR" "File not found for sourcing: $install_path"
+        fi
+    fi
 }
 
 # 🔴　ダウンロード系　ここまで　🔴　-------------------------------------------------------------------------------------------------------------------------------------------
