Update aios

diff --git a/aios b/aios
--- a/aios
+++ b/aios
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-SCRIPT_VERSION="2025.03.08-04-02"
+SCRIPT_VERSION="2025.03.08-05-00"
 echo -e "\033[7;40mUpdated to version $SCRIPT_VERSION aios \033[0m"
 
 # =========================================================
@@ -761,7 +761,7 @@ OK_download() {
     local decoded_content=""
 
     if [ -z "$file_name" ]; then
-        echo "Error: No file name provided" >&2
+        echo "ERROR: No file name provided" >&2
         return 1
     fi
 
@@ -796,12 +796,10 @@ OK_download() {
     	    debug_log "DEBUG" "Finished download function for $file_name"
     	    debug_log "DEBUG" "Sourced: $install_path"
     	    echo "$(color green "Download completed: ${read_message}$file_name - Version: $remote_version")" 
-            return 0
         fi 
 
         if [ ! -s "$install_path" ]; then
-            debug_log "ERROR" "Download failed: $file_name is empty"
-            echo "Error: Download failed: $file_name is empty." >&2
+            echo "ERROR: Download failed: $file_name is empty." >&2
             return 1
         fi
 
@@ -830,7 +828,7 @@ OK_download() {
 
         if [ "$read_mode" = "true" ] || echo "$file_name" | grep -q "common.*\\.sh"; then
 	    read_message="read"
-	        . "$install_path"
+	    . "$install_path"
 	fi
 
 	if [ "$MODE" != "aios_update" ]; then
@@ -847,12 +845,10 @@ OK_download() {
 
     elif [ "$read_mode" = "true" ] || echo "$file_name" | grep -q "common.*\\.sh"; then
 	. "$install_path"
-	return 0
     elif [ "$quiet_mode" != "true" ]; then
 	debug_log "DEBUG" "Quiet mode already up to date: $file_name - Version: $local_version"
     else
 	echo "$(color green "Already up to date: $file_name - Version: $local_version")"
-	return 0
     fi
 
     return 0
